name: safety
on: [push]

jobs:
  lint:
    #creation de machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety pytest
      - name: run safety
        run: |
          python3 -m safety
